### ISSUE TITLE
Red background for body is not cool:)

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/dsng#10]
<img width="1440" alt="screen shot 2018-11-14 at 09 03 33" src="https://user-images.githubusercontent.com/8848858/48465668-4d4d2680-e7ec-11e8-8db8-1567e9f21595.png">

**Comment by rudnitskih** [comment]
Ask me on the lesson, I will show how I can see this red color.

**Comment by IgnatSemchuk** [comment]
Sorry. It was debugging feature ))))

**Comment by IgnatSemchuk** [comment]
removed red color from BG
