### ISSUE TITLE
Optional: tablet. I think better to show address like this. 

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/dsng#12]
![image](https://user-images.githubusercontent.com/8848858/48466012-4246c600-e7ed-11e8-8864-b177eb938b38.png)

**Comment by IgnatSemchuk** [comment]
![image](https://user-images.githubusercontent.com/22999658/48627882-6ad1ea00-e9be-11e8-9fde-e89b1e19e8f5.png)
