### ISSUE TITLE
Importing fonts using @import directive is bad practice 

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/dsng#13]
https://stackoverflow.com/questions/10036977/best-way-to-include-css-why-use-import

![image](https://user-images.githubusercontent.com/8848858/48466129-92258d00-e7ed-11e8-8741-8428e01fd8ea.png)

**Comment by IgnatSemchuk** [comment]
![image](https://user-images.githubusercontent.com/22999658/48626858-b20aab80-e9bb-11e8-8185-c5043d5db0ba.png)
