### ISSUE TITLE
Finish mobile version

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/dsng#16]

**Comment by IgnatSemchuk** [comment]
done mobile markup 
To look the page, click to the [link](https://ignatsemchuk.github.io/dsng/app)

**Comment by IgnatSemchuk** [comment]
done  #dfd3b018b8f4e6fc7a3f10243ac1582c28b0fb0d
To look the page, click to the [link](https://ignatsemchuk.github.io/dsng/app)
