### ISSUE TITLE
View Project should be on the same line as '395-396 P22'

### ISSUE THREAD

**Issue by oksanarutska** [IgnatSemchuk/dsng#5]
Original: 
![image](https://user-images.githubusercontent.com/42785757/48445032-3e3f8780-e79e-11e8-900e-781e569e4e9a.png)

Your:
![image](https://user-images.githubusercontent.com/42785757/48445061-4dbed080-e79e-11e8-9de7-c817d5507406.png)

**Comment by IgnatSemchuk** [comment]
![image](https://user-images.githubusercontent.com/22999658/48703907-de156f00-ebfd-11e8-989c-77c81b6e0145.png)
