### ISSUE TITLE
Timeline title is in incorrect place

### ISSUE THREAD

**Issue by oksanarutska** [IgnatSemchuk/dsng#6]
Original: 
![image](https://user-images.githubusercontent.com/42785757/48445127-78a92480-e79e-11e8-985d-5944c3874a33.png)
Your:
![image](https://user-images.githubusercontent.com/42785757/48445153-88c10400-e79e-11e8-80a1-5a019a165185.png)

**Comment by IgnatSemchuk** [comment]
it's correct implementation. Dima allowed
