### ISSUE TITLE
Optional! Make date color = gray in "News" section

### ISSUE THREAD

**Issue by oksanarutska** [IgnatSemchuk/dsng#7]
Yours:
![image](https://user-images.githubusercontent.com/42785757/48445268-d3db1700-e79e-11e8-9e47-0339d853898d.png)
Original:
![image](https://user-images.githubusercontent.com/42785757/48445367-14d32b80-e79f-11e8-8365-c431dea4af76.png)

**Comment by IgnatSemchuk** [comment]
![image](https://user-images.githubusercontent.com/22999658/48632057-a07bd080-e9c8-11e8-924b-f9376172dc73.png)
