### ISSUE TITLE
"Staff" section. Staff job position  should not be bold

### ISSUE THREAD

**Issue by oksanarutska** [IgnatSemchuk/dsng#8]
Original:
![image](https://user-images.githubusercontent.com/42785757/48445681-cc683d80-e79f-11e8-90d0-2f3b5dba6fa4.png)
Yours:
![image](https://user-images.githubusercontent.com/42785757/48445698-da1dc300-e79f-11e8-8af5-e51e9e51c2c8.png)

**Comment by IgnatSemchuk** [comment]
![image](https://user-images.githubusercontent.com/22999658/48631836-1f243e00-e9c8-11e8-83fd-dbbaf4b3fc19.png)
